language: ruby

rvm:
  - 2.6.3

before_script:
  - chmod +x ./script/cibuild
  - chmod +x ./script/html-to-pdf.sh

script:
  - ./script/cibuild
  - - ./script/html-to-pdf.sh

branches:
  only:
    - master  #same as github pages dir

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler  #cache gems
